AWSTemplateFormatVersion: 2010-09-09

# https://s3.amazonaws.com/cloudformation.jsonize.com/cloudfront-edge-authenticator/lambda-to-http.yaml

Description: Resources for setting up the lambda part for the edge authenticator.


Resources:

  EdgeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*

  EdgeLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          {{file-read file:lambda_to_http.js indent:true}}
      Handler: index.handler
      Role: !GetAtt EdgeLambdaRole.Arn
      Runtime: nodejs12.x
      Timeout: 5
