AWSTemplateFormatVersion: 2010-09-09

# https://s3.amazonaws.com/cloudformation.jsonize.com/cloudfront-edge-authenticator/lambda-to-lambda.yaml

Description: Resources for setting up the lambda part for the edge authenticator.



Parameters:

  RequestUrl:
    Type: String
    Description: The request url rewrite for the origin Lambda function
    Default: "%uri%"

  RequestSignature:
    Type: String
    Description: Optional request signature for signing

  AwsRegion:
    Type: String
    Description: AWS region of the origin Lambda function
    Default: us-east-1

  LambdaFunctionName:
    Type: String
    Description: Name of the origin Lambda function


Resources:

  EdgeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

  EdgeLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub |
          {{file-read file:lambda_to_lambda.js indent:true}}
      Handler: index.handler
      Role: !GetAtt EdgeLambdaRole.Arn
      Runtime: nodejs16.x
      Timeout: 5

  EdgeLambdaVersion:
    Type: AWS::Lambda::Version
    DependsOn:
      - EdgeLambda
    Properties:
      FunctionName: !GetAtt EdgeLambda.Arn


Outputs:

  EdgeLambdaArn:
    Description: The arn of the Edge lambda
    Value: !GetAtt EdgeLambda.Arn